// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: tracking/v2/messages.proto

package tracking

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandAckStatus int32

const (
	CommandAckStatus_COMMAND_ACK_STATUS_UNSPECIFIED CommandAckStatus = 0
	CommandAckStatus_COMMAND_ACK_STATUS_OK          CommandAckStatus = 1
	CommandAckStatus_COMMAND_ACK_STATUS_REJECTED    CommandAckStatus = 2
	CommandAckStatus_COMMAND_ACK_STATUS_FAILED      CommandAckStatus = 3
)

// Enum value maps for CommandAckStatus.
var (
	CommandAckStatus_name = map[int32]string{
		0: "COMMAND_ACK_STATUS_UNSPECIFIED",
		1: "COMMAND_ACK_STATUS_OK",
		2: "COMMAND_ACK_STATUS_REJECTED",
		3: "COMMAND_ACK_STATUS_FAILED",
	}
	CommandAckStatus_value = map[string]int32{
		"COMMAND_ACK_STATUS_UNSPECIFIED": 0,
		"COMMAND_ACK_STATUS_OK":          1,
		"COMMAND_ACK_STATUS_REJECTED":    2,
		"COMMAND_ACK_STATUS_FAILED":      3,
	}
)

func (x CommandAckStatus) Enum() *CommandAckStatus {
	p := new(CommandAckStatus)
	*p = x
	return p
}

func (x CommandAckStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandAckStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_tracking_v2_messages_proto_enumTypes[0].Descriptor()
}

func (CommandAckStatus) Type() protoreflect.EnumType {
	return &file_tracking_v2_messages_proto_enumTypes[0]
}

func (x CommandAckStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandAckStatus.Descriptor instead.
func (CommandAckStatus) EnumDescriptor() ([]byte, []int) {
	return file_tracking_v2_messages_proto_rawDescGZIP(), []int{0}
}

type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_UNSPECIFIED     ErrorCode = 0
	ErrorCode_ERROR_CODE_AUTH            ErrorCode = 1
	ErrorCode_ERROR_CODE_TRACK_NOT_FOUND ErrorCode = 2
	ErrorCode_ERROR_CODE_FENCED          ErrorCode = 3
	ErrorCode_ERROR_CODE_TRY_AGAIN       ErrorCode = 4
	ErrorCode_ERROR_CODE_INVALID         ErrorCode = 5
	ErrorCode_ERROR_CODE_UNAUTHORIZED    ErrorCode = 6
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "ERROR_CODE_UNSPECIFIED",
		1: "ERROR_CODE_AUTH",
		2: "ERROR_CODE_TRACK_NOT_FOUND",
		3: "ERROR_CODE_FENCED",
		4: "ERROR_CODE_TRY_AGAIN",
		5: "ERROR_CODE_INVALID",
		6: "ERROR_CODE_UNAUTHORIZED",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED":     0,
		"ERROR_CODE_AUTH":            1,
		"ERROR_CODE_TRACK_NOT_FOUND": 2,
		"ERROR_CODE_FENCED":          3,
		"ERROR_CODE_TRY_AGAIN":       4,
		"ERROR_CODE_INVALID":         5,
		"ERROR_CODE_UNAUTHORIZED":    6,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_tracking_v2_messages_proto_enumTypes[1].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_tracking_v2_messages_proto_enumTypes[1]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_tracking_v2_messages_proto_rawDescGZIP(), []int{1}
}

type LatLng struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Altitude      *float64               `protobuf:"fixed64,3,opt,name=altitude,proto3,oneof" json:"altitude,omitempty"`
	Accuracy      *float64               `protobuf:"fixed64,4,opt,name=accuracy,proto3,oneof" json:"accuracy,omitempty"`
	Heading       *float64               `protobuf:"fixed64,5,opt,name=heading,proto3,oneof" json:"heading,omitempty"`
	Speed         *float64               `protobuf:"fixed64,6,opt,name=speed,proto3,oneof" json:"speed,omitempty"`
	TimestampMs   *int64                 `protobuf:"varint,7,opt,name=timestamp_ms,json=timestampMs,proto3,oneof" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LatLng) Reset() {
	*x = LatLng{}
	mi := &file_tracking_v2_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatLng) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatLng) ProtoMessage() {}

func (x *LatLng) ProtoReflect() protoreflect.Message {
	mi := &file_tracking_v2_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatLng.ProtoReflect.Descriptor instead.
func (*LatLng) Descriptor() ([]byte, []int) {
	return file_tracking_v2_messages_proto_rawDescGZIP(), []int{0}
}

func (x *LatLng) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *LatLng) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *LatLng) GetAltitude() float64 {
	if x != nil && x.Altitude != nil {
		return *x.Altitude
	}
	return 0
}

func (x *LatLng) GetAccuracy() float64 {
	if x != nil && x.Accuracy != nil {
		return *x.Accuracy
	}
	return 0
}

func (x *LatLng) GetHeading() float64 {
	if x != nil && x.Heading != nil {
		return *x.Heading
	}
	return 0
}

func (x *LatLng) GetSpeed() float64 {
	if x != nil && x.Speed != nil {
		return *x.Speed
	}
	return 0
}

func (x *LatLng) GetTimestampMs() int64 {
	if x != nil && x.TimestampMs != nil {
		return *x.TimestampMs
	}
	return 0
}

type ClientMsg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*ClientMsg_Resume
	//	*ClientMsg_TrackStart
	//	*ClientMsg_TrackStop
	//	*ClientMsg_LocationAdd
	//	*ClientMsg_LocationBatch
	//	*ClientMsg_Subscribe
	//	*ClientMsg_Unsubscribe
	//	*ClientMsg_Ping
	//	*ClientMsg_Event
	//	*ClientMsg_CommandAck
	Body          isClientMsg_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMsg) Reset() {
	*x = ClientMsg{}
	mi := &file_tracking_v2_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMsg) ProtoMessage() {}

func (x *ClientMsg) ProtoReflect() protoreflect.Message {
	mi := &file_tracking_v2_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMsg.ProtoReflect.Descriptor instead.
func (*ClientMsg) Descriptor() ([]byte, []int) {
	return file_tracking_v2_messages_proto_rawDescGZIP(), []int{1}
}

func (x *ClientMsg) GetBody() isClientMsg_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ClientMsg) GetResume() *Resume {
	if x != nil {
		if x, ok := x.Body.(*ClientMsg_Resume); ok {
			return x.Resume
		}
	}
	return nil
}

func (x *ClientMsg) GetTrackStart() *TrackStart {
	if x != nil {
		if x, ok := x.Body.(*ClientMsg_TrackStart); ok {
			return x.TrackStart
		}
	}
	return nil
}

func (x *ClientMsg) GetTrackStop() *TrackStop {
	if x != nil {
		if x, ok := x.Body.(*ClientMsg_TrackStop); ok {
			return x.TrackStop
		}
	}
	return nil
}

func (x *ClientMsg) GetLocationAdd() *LocationAdd {
	if x != nil {
		if x, ok := x.Body.(*ClientMsg_LocationAdd); ok {
			return x.LocationAdd
		}
	}
	return nil
}

func (x *ClientMsg) GetLocationBatch() *LocationBatch {
	if x != nil {
		if x, ok := x.Body.(*ClientMsg_LocationBatch); ok {
			return x.LocationBatch
		}
	}
	return nil
}

func (x *ClientMsg) GetSubscribe() *Subscribe {
	if x != nil {
		if x, ok := x.Body.(*ClientMsg_Subscribe); ok {
			return x.Subscribe
		}
	}
	return nil
}

func (x *ClientMsg) GetUnsubscribe() *Unsubscribe {
	if x != nil {
		if x, ok := x.Body.(*ClientMsg_Unsubscribe); ok {
			return x.Unsubscribe
		}
	}
	return nil
}

func (x *ClientMsg) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Body.(*ClientMsg_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *ClientMsg) GetEvent() *Event {
	if x != nil {
		if x, ok := x.Body.(*ClientMsg_Event); ok {
			return x.Event
		}
	}
	return nil
}

func (x *ClientMsg) GetCommandAck() *CommandAck {
	if x != nil {
		if x, ok := x.Body.(*ClientMsg_CommandAck); ok {
			return x.CommandAck
		}
	}
	return nil
}

type isClientMsg_Body interface {
	isClientMsg_Body()
}

type ClientMsg_Resume struct {
	Resume *Resume `protobuf:"bytes,1,opt,name=resume,proto3,oneof"`
}

type ClientMsg_TrackStart struct {
	TrackStart *TrackStart `protobuf:"bytes,2,opt,name=track_start,json=trackStart,proto3,oneof"`
}

type ClientMsg_TrackStop struct {
	TrackStop *TrackStop `protobuf:"bytes,3,opt,name=track_stop,json=trackStop,proto3,oneof"`
}

type ClientMsg_LocationAdd struct {
	LocationAdd *LocationAdd `protobuf:"bytes,4,opt,name=location_add,json=locationAdd,proto3,oneof"`
}

type ClientMsg_LocationBatch struct {
	LocationBatch *LocationBatch `protobuf:"bytes,5,opt,name=location_batch,json=locationBatch,proto3,oneof"`
}

type ClientMsg_Subscribe struct {
	Subscribe *Subscribe `protobuf:"bytes,6,opt,name=subscribe,proto3,oneof"`
}

type ClientMsg_Unsubscribe struct {
	Unsubscribe *Unsubscribe `protobuf:"bytes,7,opt,name=unsubscribe,proto3,oneof"`
}

type ClientMsg_Ping struct {
	Ping *Ping `protobuf:"bytes,8,opt,name=ping,proto3,oneof"`
}

type ClientMsg_Event struct {
	// Opaque fan-out only (not stored / not resumed). ≤4 KiB, ≤1 Hz per track.
	Event *Event `protobuf:"bytes,9,opt,name=event,proto3,oneof"`
}

type ClientMsg_CommandAck struct {
	CommandAck *CommandAck `protobuf:"bytes,10,opt,name=command_ack,json=commandAck,proto3,oneof"`
}

func (*ClientMsg_Resume) isClientMsg_Body() {}

func (*ClientMsg_TrackStart) isClientMsg_Body() {}

func (*ClientMsg_TrackStop) isClientMsg_Body() {}

func (*ClientMsg_LocationAdd) isClientMsg_Body() {}

func (*ClientMsg_LocationBatch) isClientMsg_Body() {}

func (*ClientMsg_Subscribe) isClientMsg_Body() {}

func (*ClientMsg_Unsubscribe) isClientMsg_Body() {}

func (*ClientMsg_Ping) isClientMsg_Body() {}

func (*ClientMsg_Event) isClientMsg_Body() {}

func (*ClientMsg_CommandAck) isClientMsg_Body() {}

type Resume struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackUid      string                 `protobuf:"bytes,1,opt,name=track_uid,json=trackUid,proto3" json:"track_uid,omitempty"`
	LastClientSeq uint64                 `protobuf:"varint,2,opt,name=last_client_seq,json=lastClientSeq,proto3" json:"last_client_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resume) Reset() {
	*x = Resume{}
	mi := &file_tracking_v2_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resume) ProtoMessage() {}

func (x *Resume) ProtoReflect() protoreflect.Message {
	mi := &file_tracking_v2_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resume.ProtoReflect.Descriptor instead.
func (*Resume) Descriptor() ([]byte, []int) {
	return file_tracking_v2_messages_proto_rawDescGZIP(), []int{2}
}

func (x *Resume) GetTrackUid() string {
	if x != nil {
		return x.TrackUid
	}
	return ""
}

func (x *Resume) GetLastClientSeq() uint64 {
	if x != nil {
		return x.LastClientSeq
	}
	return 0
}

type TrackStart struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Location *LatLng                `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	Route    []*LatLng              `protobuf:"bytes,2,rep,name=route,proto3" json:"route,omitempty"`
	// Opaque app metadata (trip/order/…). ≤4 KiB. Not interpreted by server.
	Metadata      []byte `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackStart) Reset() {
	*x = TrackStart{}
	mi := &file_tracking_v2_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackStart) ProtoMessage() {}

func (x *TrackStart) ProtoReflect() protoreflect.Message {
	mi := &file_tracking_v2_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackStart.ProtoReflect.Descriptor instead.
func (*TrackStart) Descriptor() ([]byte, []int) {
	return file_tracking_v2_messages_proto_rawDescGZIP(), []int{3}
}

func (x *TrackStart) GetLocation() *LatLng {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *TrackStart) GetRoute() []*LatLng {
	if x != nil {
		return x.Route
	}
	return nil
}

func (x *TrackStart) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type TrackStop struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackUid      string                 `protobuf:"bytes,1,opt,name=track_uid,json=trackUid,proto3" json:"track_uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackStop) Reset() {
	*x = TrackStop{}
	mi := &file_tracking_v2_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackStop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackStop) ProtoMessage() {}

func (x *TrackStop) ProtoReflect() protoreflect.Message {
	mi := &file_tracking_v2_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackStop.ProtoReflect.Descriptor instead.
func (*TrackStop) Descriptor() ([]byte, []int) {
	return file_tracking_v2_messages_proto_rawDescGZIP(), []int{4}
}

func (x *TrackStop) GetTrackUid() string {
	if x != nil {
		return x.TrackUid
	}
	return ""
}

type LocationAdd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackUid      string                 `protobuf:"bytes,1,opt,name=track_uid,json=trackUid,proto3" json:"track_uid,omitempty"`
	ClientSeq     uint64                 `protobuf:"varint,2,opt,name=client_seq,json=clientSeq,proto3" json:"client_seq,omitempty"`
	Point         *LatLng                `protobuf:"bytes,3,opt,name=point,proto3" json:"point,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocationAdd) Reset() {
	*x = LocationAdd{}
	mi := &file_tracking_v2_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationAdd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationAdd) ProtoMessage() {}

func (x *LocationAdd) ProtoReflect() protoreflect.Message {
	mi := &file_tracking_v2_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationAdd.ProtoReflect.Descriptor instead.
func (*LocationAdd) Descriptor() ([]byte, []int) {
	return file_tracking_v2_messages_proto_rawDescGZIP(), []int{5}
}

func (x *LocationAdd) GetTrackUid() string {
	if x != nil {
		return x.TrackUid
	}
	return ""
}

func (x *LocationAdd) GetClientSeq() uint64 {
	if x != nil {
		return x.ClientSeq
	}
	return 0
}

func (x *LocationAdd) GetPoint() *LatLng {
	if x != nil {
		return x.Point
	}
	return nil
}

type LocationBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackUid      string                 `protobuf:"bytes,1,opt,name=track_uid,json=trackUid,proto3" json:"track_uid,omitempty"`
	ClientSeq     uint64                 `protobuf:"varint,2,opt,name=client_seq,json=clientSeq,proto3" json:"client_seq,omitempty"` // seq of last point in batch
	Points        []*LatLng              `protobuf:"bytes,3,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocationBatch) Reset() {
	*x = LocationBatch{}
	mi := &file_tracking_v2_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationBatch) ProtoMessage() {}

func (x *LocationBatch) ProtoReflect() protoreflect.Message {
	mi := &file_tracking_v2_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationBatch.ProtoReflect.Descriptor instead.
func (*LocationBatch) Descriptor() ([]byte, []int) {
	return file_tracking_v2_messages_proto_rawDescGZIP(), []int{6}
}

func (x *LocationBatch) GetTrackUid() string {
	if x != nil {
		return x.TrackUid
	}
	return ""
}

func (x *LocationBatch) GetClientSeq() uint64 {
	if x != nil {
		return x.ClientSeq
	}
	return 0
}

func (x *LocationBatch) GetPoints() []*LatLng {
	if x != nil {
		return x.Points
	}
	return nil
}

type Subscribe struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	DeviceUid string                 `protobuf:"bytes,1,opt,name=device_uid,json=deviceUid,proto3" json:"device_uid,omitempty"`
	// Unset = true (receive events). Set false to skip EventAdded fan-out.
	IncludeEvents *bool `protobuf:"varint,2,opt,name=include_events,json=includeEvents,proto3,oneof" json:"include_events,omitempty"`
	// Extra per-listener throttle for LocationAdded (0 = none beyond server cap).
	MinLocationIntervalMs uint32 `protobuf:"varint,3,opt,name=min_location_interval_ms,json=minLocationIntervalMs,proto3" json:"min_location_interval_ms,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Subscribe) Reset() {
	*x = Subscribe{}
	mi := &file_tracking_v2_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscribe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscribe) ProtoMessage() {}

func (x *Subscribe) ProtoReflect() protoreflect.Message {
	mi := &file_tracking_v2_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscribe.ProtoReflect.Descriptor instead.
func (*Subscribe) Descriptor() ([]byte, []int) {
	return file_tracking_v2_messages_proto_rawDescGZIP(), []int{7}
}

func (x *Subscribe) GetDeviceUid() string {
	if x != nil {
		return x.DeviceUid
	}
	return ""
}

func (x *Subscribe) GetIncludeEvents() bool {
	if x != nil && x.IncludeEvents != nil {
		return *x.IncludeEvents
	}
	return false
}

func (x *Subscribe) GetMinLocationIntervalMs() uint32 {
	if x != nil {
		return x.MinLocationIntervalMs
	}
	return 0
}

type Unsubscribe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceUid     string                 `protobuf:"bytes,1,opt,name=device_uid,json=deviceUid,proto3" json:"device_uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Unsubscribe) Reset() {
	*x = Unsubscribe{}
	mi := &file_tracking_v2_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Unsubscribe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unsubscribe) ProtoMessage() {}

func (x *Unsubscribe) ProtoReflect() protoreflect.Message {
	mi := &file_tracking_v2_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unsubscribe.ProtoReflect.Descriptor instead.
func (*Unsubscribe) Descriptor() ([]byte, []int) {
	return file_tracking_v2_messages_proto_rawDescGZIP(), []int{8}
}

func (x *Unsubscribe) GetDeviceUid() string {
	if x != nil {
		return x.DeviceUid
	}
	return ""
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_tracking_v2_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_tracking_v2_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_tracking_v2_messages_proto_rawDescGZIP(), []int{9}
}

// Device → subscribers custom payload. App encodes type inside `payload`.
type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackUid      string                 `protobuf:"bytes,1,opt,name=track_uid,json=trackUid,proto3" json:"track_uid,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	TimestampMs   *int64                 `protobuf:"varint,3,opt,name=timestamp_ms,json=timestampMs,proto3,oneof" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_tracking_v2_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_tracking_v2_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_tracking_v2_messages_proto_rawDescGZIP(), []int{10}
}

func (x *Event) GetTrackUid() string {
	if x != nil {
		return x.TrackUid
	}
	return ""
}

func (x *Event) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetTimestampMs() int64 {
	if x != nil && x.TimestampMs != nil {
		return *x.TimestampMs
	}
	return 0
}

type CommandAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Status        CommandAckStatus       `protobuf:"varint,2,opt,name=status,proto3,enum=tracking.v2.CommandAckStatus" json:"status,omitempty"`
	Message       *string                `protobuf:"bytes,3,opt,name=message,proto3,oneof" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandAck) Reset() {
	*x = CommandAck{}
	mi := &file_tracking_v2_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandAck) ProtoMessage() {}

func (x *CommandAck) ProtoReflect() protoreflect.Message {
	mi := &file_tracking_v2_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandAck.ProtoReflect.Descriptor instead.
func (*CommandAck) Descriptor() ([]byte, []int) {
	return file_tracking_v2_messages_proto_rawDescGZIP(), []int{11}
}

func (x *CommandAck) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandAck) GetStatus() CommandAckStatus {
	if x != nil {
		return x.Status
	}
	return CommandAckStatus_COMMAND_ACK_STATUS_UNSPECIFIED
}

func (x *CommandAck) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

type ServerMsg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*ServerMsg_Hello
	//	*ServerMsg_Relocate
	//	*ServerMsg_ResumeOk
	//	*ServerMsg_TrackStarted
	//	*ServerMsg_TrackStopped
	//	*ServerMsg_LocationAdded
	//	*ServerMsg_Subscribed
	//	*ServerMsg_ListenerSubscribed
	//	*ServerMsg_Error
	//	*ServerMsg_Pong
	//	*ServerMsg_EventAdded
	//	*ServerMsg_Command
	//	*ServerMsg_DevicePresence
	Body          isServerMsg_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMsg) Reset() {
	*x = ServerMsg{}
	mi := &file_tracking_v2_messages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMsg) ProtoMessage() {}

func (x *ServerMsg) ProtoReflect() protoreflect.Message {
	mi := &file_tracking_v2_messages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMsg.ProtoReflect.Descriptor instead.
func (*ServerMsg) Descriptor() ([]byte, []int) {
	return file_tracking_v2_messages_proto_rawDescGZIP(), []int{12}
}

func (x *ServerMsg) GetBody() isServerMsg_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ServerMsg) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Body.(*ServerMsg_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *ServerMsg) GetRelocate() *Relocate {
	if x != nil {
		if x, ok := x.Body.(*ServerMsg_Relocate); ok {
			return x.Relocate
		}
	}
	return nil
}

func (x *ServerMsg) GetResumeOk() *ResumeOk {
	if x != nil {
		if x, ok := x.Body.(*ServerMsg_ResumeOk); ok {
			return x.ResumeOk
		}
	}
	return nil
}

func (x *ServerMsg) GetTrackStarted() *TrackStarted {
	if x != nil {
		if x, ok := x.Body.(*ServerMsg_TrackStarted); ok {
			return x.TrackStarted
		}
	}
	return nil
}

func (x *ServerMsg) GetTrackStopped() *TrackStopped {
	if x != nil {
		if x, ok := x.Body.(*ServerMsg_TrackStopped); ok {
			return x.TrackStopped
		}
	}
	return nil
}

func (x *ServerMsg) GetLocationAdded() *LocationAdded {
	if x != nil {
		if x, ok := x.Body.(*ServerMsg_LocationAdded); ok {
			return x.LocationAdded
		}
	}
	return nil
}

func (x *ServerMsg) GetSubscribed() *Subscribed {
	if x != nil {
		if x, ok := x.Body.(*ServerMsg_Subscribed); ok {
			return x.Subscribed
		}
	}
	return nil
}

func (x *ServerMsg) GetListenerSubscribed() *ListenerSubscribed {
	if x != nil {
		if x, ok := x.Body.(*ServerMsg_ListenerSubscribed); ok {
			return x.ListenerSubscribed
		}
	}
	return nil
}

func (x *ServerMsg) GetError() *Error {
	if x != nil {
		if x, ok := x.Body.(*ServerMsg_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *ServerMsg) GetPong() *Pong {
	if x != nil {
		if x, ok := x.Body.(*ServerMsg_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

func (x *ServerMsg) GetEventAdded() *EventAdded {
	if x != nil {
		if x, ok := x.Body.(*ServerMsg_EventAdded); ok {
			return x.EventAdded
		}
	}
	return nil
}

func (x *ServerMsg) GetCommand() *Command {
	if x != nil {
		if x, ok := x.Body.(*ServerMsg_Command); ok {
			return x.Command
		}
	}
	return nil
}

func (x *ServerMsg) GetDevicePresence() *DevicePresence {
	if x != nil {
		if x, ok := x.Body.(*ServerMsg_DevicePresence); ok {
			return x.DevicePresence
		}
	}
	return nil
}

type isServerMsg_Body interface {
	isServerMsg_Body()
}

type ServerMsg_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type ServerMsg_Relocate struct {
	Relocate *Relocate `protobuf:"bytes,2,opt,name=relocate,proto3,oneof"`
}

type ServerMsg_ResumeOk struct {
	ResumeOk *ResumeOk `protobuf:"bytes,3,opt,name=resume_ok,json=resumeOk,proto3,oneof"`
}

type ServerMsg_TrackStarted struct {
	TrackStarted *TrackStarted `protobuf:"bytes,4,opt,name=track_started,json=trackStarted,proto3,oneof"`
}

type ServerMsg_TrackStopped struct {
	TrackStopped *TrackStopped `protobuf:"bytes,5,opt,name=track_stopped,json=trackStopped,proto3,oneof"`
}

type ServerMsg_LocationAdded struct {
	LocationAdded *LocationAdded `protobuf:"bytes,6,opt,name=location_added,json=locationAdded,proto3,oneof"`
}

type ServerMsg_Subscribed struct {
	Subscribed *Subscribed `protobuf:"bytes,7,opt,name=subscribed,proto3,oneof"`
}

type ServerMsg_ListenerSubscribed struct {
	ListenerSubscribed *ListenerSubscribed `protobuf:"bytes,8,opt,name=listener_subscribed,json=listenerSubscribed,proto3,oneof"`
}

type ServerMsg_Error struct {
	Error *Error `protobuf:"bytes,9,opt,name=error,proto3,oneof"`
}

type ServerMsg_Pong struct {
	Pong *Pong `protobuf:"bytes,10,opt,name=pong,proto3,oneof"`
}

type ServerMsg_EventAdded struct {
	EventAdded *EventAdded `protobuf:"bytes,11,opt,name=event_added,json=eventAdded,proto3,oneof"`
}

type ServerMsg_Command struct {
	// Server → device (HTTP inject). Opaque, ≤4 KiB, not stored.
	Command *Command `protobuf:"bytes,12,opt,name=command,proto3,oneof"`
}

type ServerMsg_DevicePresence struct {
	DevicePresence *DevicePresence `protobuf:"bytes,13,opt,name=device_presence,json=devicePresence,proto3,oneof"`
}

func (*ServerMsg_Hello) isServerMsg_Body() {}

func (*ServerMsg_Relocate) isServerMsg_Body() {}

func (*ServerMsg_ResumeOk) isServerMsg_Body() {}

func (*ServerMsg_TrackStarted) isServerMsg_Body() {}

func (*ServerMsg_TrackStopped) isServerMsg_Body() {}

func (*ServerMsg_LocationAdded) isServerMsg_Body() {}

func (*ServerMsg_Subscribed) isServerMsg_Body() {}

func (*ServerMsg_ListenerSubscribed) isServerMsg_Body() {}

func (*ServerMsg_Error) isServerMsg_Body() {}

func (*ServerMsg_Pong) isServerMsg_Body() {}

func (*ServerMsg_EventAdded) isServerMsg_Body() {}

func (*ServerMsg_Command) isServerMsg_Body() {}

func (*ServerMsg_DevicePresence) isServerMsg_Body() {}

type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Shard         uint32                 `protobuf:"varint,2,opt,name=shard,proto3" json:"shard,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_tracking_v2_messages_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_tracking_v2_messages_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_tracking_v2_messages_proto_rawDescGZIP(), []int{13}
}

func (x *Hello) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Hello) GetShard() uint32 {
	if x != nil {
		return x.Shard
	}
	return 0
}

type Relocate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint      string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	RetryAfterMs  uint32                 `protobuf:"varint,2,opt,name=retry_after_ms,json=retryAfterMs,proto3" json:"retry_after_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Relocate) Reset() {
	*x = Relocate{}
	mi := &file_tracking_v2_messages_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Relocate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Relocate) ProtoMessage() {}

func (x *Relocate) ProtoReflect() protoreflect.Message {
	mi := &file_tracking_v2_messages_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Relocate.ProtoReflect.Descriptor instead.
func (*Relocate) Descriptor() ([]byte, []int) {
	return file_tracking_v2_messages_proto_rawDescGZIP(), []int{14}
}

func (x *Relocate) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *Relocate) GetRetryAfterMs() uint32 {
	if x != nil {
		return x.RetryAfterMs
	}
	return 0
}

type ResumeOk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackUid      string                 `protobuf:"bytes,1,opt,name=track_uid,json=trackUid,proto3" json:"track_uid,omitempty"`
	LastAckedSeq  uint64                 `protobuf:"varint,2,opt,name=last_acked_seq,json=lastAckedSeq,proto3" json:"last_acked_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeOk) Reset() {
	*x = ResumeOk{}
	mi := &file_tracking_v2_messages_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeOk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeOk) ProtoMessage() {}

func (x *ResumeOk) ProtoReflect() protoreflect.Message {
	mi := &file_tracking_v2_messages_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeOk.ProtoReflect.Descriptor instead.
func (*ResumeOk) Descriptor() ([]byte, []int) {
	return file_tracking_v2_messages_proto_rawDescGZIP(), []int{15}
}

func (x *ResumeOk) GetTrackUid() string {
	if x != nil {
		return x.TrackUid
	}
	return ""
}

func (x *ResumeOk) GetLastAckedSeq() uint64 {
	if x != nil {
		return x.LastAckedSeq
	}
	return 0
}

type TrackStarted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackUid      string                 `protobuf:"bytes,1,opt,name=track_uid,json=trackUid,proto3" json:"track_uid,omitempty"`
	Metadata      []byte                 `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackStarted) Reset() {
	*x = TrackStarted{}
	mi := &file_tracking_v2_messages_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackStarted) ProtoMessage() {}

func (x *TrackStarted) ProtoReflect() protoreflect.Message {
	mi := &file_tracking_v2_messages_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackStarted.ProtoReflect.Descriptor instead.
func (*TrackStarted) Descriptor() ([]byte, []int) {
	return file_tracking_v2_messages_proto_rawDescGZIP(), []int{16}
}

func (x *TrackStarted) GetTrackUid() string {
	if x != nil {
		return x.TrackUid
	}
	return ""
}

func (x *TrackStarted) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type TrackStopped struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackUid      string                 `protobuf:"bytes,1,opt,name=track_uid,json=trackUid,proto3" json:"track_uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackStopped) Reset() {
	*x = TrackStopped{}
	mi := &file_tracking_v2_messages_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackStopped) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackStopped) ProtoMessage() {}

func (x *TrackStopped) ProtoReflect() protoreflect.Message {
	mi := &file_tracking_v2_messages_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackStopped.ProtoReflect.Descriptor instead.
func (*TrackStopped) Descriptor() ([]byte, []int) {
	return file_tracking_v2_messages_proto_rawDescGZIP(), []int{17}
}

func (x *TrackStopped) GetTrackUid() string {
	if x != nil {
		return x.TrackUid
	}
	return ""
}

type LocationAdded struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceUid     string                 `protobuf:"bytes,1,opt,name=device_uid,json=deviceUid,proto3" json:"device_uid,omitempty"`
	TrackUid      string                 `protobuf:"bytes,2,opt,name=track_uid,json=trackUid,proto3" json:"track_uid,omitempty"`
	Point         *LatLng                `protobuf:"bytes,3,opt,name=point,proto3" json:"point,omitempty"`
	ClientSeq     uint64                 `protobuf:"varint,4,opt,name=client_seq,json=clientSeq,proto3" json:"client_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocationAdded) Reset() {
	*x = LocationAdded{}
	mi := &file_tracking_v2_messages_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationAdded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationAdded) ProtoMessage() {}

func (x *LocationAdded) ProtoReflect() protoreflect.Message {
	mi := &file_tracking_v2_messages_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationAdded.ProtoReflect.Descriptor instead.
func (*LocationAdded) Descriptor() ([]byte, []int) {
	return file_tracking_v2_messages_proto_rawDescGZIP(), []int{18}
}

func (x *LocationAdded) GetDeviceUid() string {
	if x != nil {
		return x.DeviceUid
	}
	return ""
}

func (x *LocationAdded) GetTrackUid() string {
	if x != nil {
		return x.TrackUid
	}
	return ""
}

func (x *LocationAdded) GetPoint() *LatLng {
	if x != nil {
		return x.Point
	}
	return nil
}

func (x *LocationAdded) GetClientSeq() uint64 {
	if x != nil {
		return x.ClientSeq
	}
	return 0
}

type Subscribed struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DeviceUid         string                 `protobuf:"bytes,1,opt,name=device_uid,json=deviceUid,proto3" json:"device_uid,omitempty"`
	TrackUid          string                 `protobuf:"bytes,2,opt,name=track_uid,json=trackUid,proto3" json:"track_uid,omitempty"`
	LastLocation      *LatLng                `protobuf:"bytes,3,opt,name=last_location,json=lastLocation,proto3" json:"last_location,omitempty"`
	Route             []*LatLng              `protobuf:"bytes,4,rep,name=route,proto3" json:"route,omitempty"`
	Locations         []*LatLng              `protobuf:"bytes,5,rep,name=locations,proto3" json:"locations,omitempty"`
	EstimatedDistance float64                `protobuf:"fixed64,6,opt,name=estimated_distance,json=estimatedDistance,proto3" json:"estimated_distance,omitempty"`
	EstimatedDuration float64                `protobuf:"fixed64,7,opt,name=estimated_duration,json=estimatedDuration,proto3" json:"estimated_duration,omitempty"`
	StartLocationName string                 `protobuf:"bytes,8,opt,name=start_location_name,json=startLocationName,proto3" json:"start_location_name,omitempty"`
	EndLocationName   string                 `protobuf:"bytes,9,opt,name=end_location_name,json=endLocationName,proto3" json:"end_location_name,omitempty"`
	Metadata          []byte                 `protobuf:"bytes,10,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Online            bool                   `protobuf:"varint,11,opt,name=online,proto3" json:"online,omitempty"`
	LastSeenMs        *int64                 `protobuf:"varint,12,opt,name=last_seen_ms,json=lastSeenMs,proto3,oneof" json:"last_seen_ms,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Subscribed) Reset() {
	*x = Subscribed{}
	mi := &file_tracking_v2_messages_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscribed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscribed) ProtoMessage() {}

func (x *Subscribed) ProtoReflect() protoreflect.Message {
	mi := &file_tracking_v2_messages_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscribed.ProtoReflect.Descriptor instead.
func (*Subscribed) Descriptor() ([]byte, []int) {
	return file_tracking_v2_messages_proto_rawDescGZIP(), []int{19}
}

func (x *Subscribed) GetDeviceUid() string {
	if x != nil {
		return x.DeviceUid
	}
	return ""
}

func (x *Subscribed) GetTrackUid() string {
	if x != nil {
		return x.TrackUid
	}
	return ""
}

func (x *Subscribed) GetLastLocation() *LatLng {
	if x != nil {
		return x.LastLocation
	}
	return nil
}

func (x *Subscribed) GetRoute() []*LatLng {
	if x != nil {
		return x.Route
	}
	return nil
}

func (x *Subscribed) GetLocations() []*LatLng {
	if x != nil {
		return x.Locations
	}
	return nil
}

func (x *Subscribed) GetEstimatedDistance() float64 {
	if x != nil {
		return x.EstimatedDistance
	}
	return 0
}

func (x *Subscribed) GetEstimatedDuration() float64 {
	if x != nil {
		return x.EstimatedDuration
	}
	return 0
}

func (x *Subscribed) GetStartLocationName() string {
	if x != nil {
		return x.StartLocationName
	}
	return ""
}

func (x *Subscribed) GetEndLocationName() string {
	if x != nil {
		return x.EndLocationName
	}
	return ""
}

func (x *Subscribed) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Subscribed) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *Subscribed) GetLastSeenMs() int64 {
	if x != nil && x.LastSeenMs != nil {
		return *x.LastSeenMs
	}
	return 0
}

type ListenerSubscribed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListenerSubscribed) Reset() {
	*x = ListenerSubscribed{}
	mi := &file_tracking_v2_messages_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListenerSubscribed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListenerSubscribed) ProtoMessage() {}

func (x *ListenerSubscribed) ProtoReflect() protoreflect.Message {
	mi := &file_tracking_v2_messages_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListenerSubscribed.ProtoReflect.Descriptor instead.
func (*ListenerSubscribed) Descriptor() ([]byte, []int) {
	return file_tracking_v2_messages_proto_rawDescGZIP(), []int{20}
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=tracking.v2.ErrorCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TrackUid      *string                `protobuf:"bytes,3,opt,name=track_uid,json=trackUid,proto3,oneof" json:"track_uid,omitempty"`
	RetryAfterMs  *uint32                `protobuf:"varint,4,opt,name=retry_after_ms,json=retryAfterMs,proto3,oneof" json:"retry_after_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_tracking_v2_messages_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_tracking_v2_messages_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_tracking_v2_messages_proto_rawDescGZIP(), []int{21}
}

func (x *Error) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetTrackUid() string {
	if x != nil && x.TrackUid != nil {
		return *x.TrackUid
	}
	return ""
}

func (x *Error) GetRetryAfterMs() uint32 {
	if x != nil && x.RetryAfterMs != nil {
		return *x.RetryAfterMs
	}
	return 0
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_tracking_v2_messages_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_tracking_v2_messages_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_tracking_v2_messages_proto_rawDescGZIP(), []int{22}
}

type EventAdded struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceUid     string                 `protobuf:"bytes,1,opt,name=device_uid,json=deviceUid,proto3" json:"device_uid,omitempty"`
	TrackUid      string                 `protobuf:"bytes,2,opt,name=track_uid,json=trackUid,proto3" json:"track_uid,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	TimestampMs   *int64                 `protobuf:"varint,4,opt,name=timestamp_ms,json=timestampMs,proto3,oneof" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventAdded) Reset() {
	*x = EventAdded{}
	mi := &file_tracking_v2_messages_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventAdded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventAdded) ProtoMessage() {}

func (x *EventAdded) ProtoReflect() protoreflect.Message {
	mi := &file_tracking_v2_messages_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventAdded.ProtoReflect.Descriptor instead.
func (*EventAdded) Descriptor() ([]byte, []int) {
	return file_tracking_v2_messages_proto_rawDescGZIP(), []int{23}
}

func (x *EventAdded) GetDeviceUid() string {
	if x != nil {
		return x.DeviceUid
	}
	return ""
}

func (x *EventAdded) GetTrackUid() string {
	if x != nil {
		return x.TrackUid
	}
	return ""
}

func (x *EventAdded) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EventAdded) GetTimestampMs() int64 {
	if x != nil && x.TimestampMs != nil {
		return *x.TimestampMs
	}
	return 0
}

// Injected toward an online device session (see POST /v2/devices/{uid}/command).
type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	TimestampMs   *int64                 `protobuf:"varint,3,opt,name=timestamp_ms,json=timestampMs,proto3,oneof" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_tracking_v2_messages_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_tracking_v2_messages_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_tracking_v2_messages_proto_rawDescGZIP(), []int{24}
}

func (x *Command) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *Command) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Command) GetTimestampMs() int64 {
	if x != nil && x.TimestampMs != nil {
		return *x.TimestampMs
	}
	return 0
}

type DevicePresence struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceUid     string                 `protobuf:"bytes,1,opt,name=device_uid,json=deviceUid,proto3" json:"device_uid,omitempty"`
	Online        bool                   `protobuf:"varint,2,opt,name=online,proto3" json:"online,omitempty"`
	LastSeenMs    *int64                 `protobuf:"varint,3,opt,name=last_seen_ms,json=lastSeenMs,proto3,oneof" json:"last_seen_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DevicePresence) Reset() {
	*x = DevicePresence{}
	mi := &file_tracking_v2_messages_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DevicePresence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DevicePresence) ProtoMessage() {}

func (x *DevicePresence) ProtoReflect() protoreflect.Message {
	mi := &file_tracking_v2_messages_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DevicePresence.ProtoReflect.Descriptor instead.
func (*DevicePresence) Descriptor() ([]byte, []int) {
	return file_tracking_v2_messages_proto_rawDescGZIP(), []int{25}
}

func (x *DevicePresence) GetDeviceUid() string {
	if x != nil {
		return x.DeviceUid
	}
	return ""
}

func (x *DevicePresence) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *DevicePresence) GetLastSeenMs() int64 {
	if x != nil && x.LastSeenMs != nil {
		return *x.LastSeenMs
	}
	return 0
}

var File_tracking_v2_messages_proto protoreflect.FileDescriptor

const file_tracking_v2_messages_proto_rawDesc = "" +
	"\n" +
	"\x1atracking/v2/messages.proto\x12\vtracking.v2\"\xa7\x02\n" +
	"\x06LatLng\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x1f\n" +
	"\baltitude\x18\x03 \x01(\x01H\x00R\baltitude\x88\x01\x01\x12\x1f\n" +
	"\baccuracy\x18\x04 \x01(\x01H\x01R\baccuracy\x88\x01\x01\x12\x1d\n" +
	"\aheading\x18\x05 \x01(\x01H\x02R\aheading\x88\x01\x01\x12\x19\n" +
	"\x05speed\x18\x06 \x01(\x01H\x03R\x05speed\x88\x01\x01\x12&\n" +
	"\ftimestamp_ms\x18\a \x01(\x03H\x04R\vtimestampMs\x88\x01\x01B\v\n" +
	"\t_altitudeB\v\n" +
	"\t_accuracyB\n" +
	"\n" +
	"\b_headingB\b\n" +
	"\x06_speedB\x0f\n" +
	"\r_timestamp_ms\"\xc2\x04\n" +
	"\tClientMsg\x12-\n" +
	"\x06resume\x18\x01 \x01(\v2\x13.tracking.v2.ResumeH\x00R\x06resume\x12:\n" +
	"\vtrack_start\x18\x02 \x01(\v2\x17.tracking.v2.TrackStartH\x00R\n" +
	"trackStart\x127\n" +
	"\n" +
	"track_stop\x18\x03 \x01(\v2\x16.tracking.v2.TrackStopH\x00R\ttrackStop\x12=\n" +
	"\flocation_add\x18\x04 \x01(\v2\x18.tracking.v2.LocationAddH\x00R\vlocationAdd\x12C\n" +
	"\x0elocation_batch\x18\x05 \x01(\v2\x1a.tracking.v2.LocationBatchH\x00R\rlocationBatch\x126\n" +
	"\tsubscribe\x18\x06 \x01(\v2\x16.tracking.v2.SubscribeH\x00R\tsubscribe\x12<\n" +
	"\vunsubscribe\x18\a \x01(\v2\x18.tracking.v2.UnsubscribeH\x00R\vunsubscribe\x12'\n" +
	"\x04ping\x18\b \x01(\v2\x11.tracking.v2.PingH\x00R\x04ping\x12*\n" +
	"\x05event\x18\t \x01(\v2\x12.tracking.v2.EventH\x00R\x05event\x12:\n" +
	"\vcommand_ack\x18\n" +
	" \x01(\v2\x17.tracking.v2.CommandAckH\x00R\n" +
	"commandAckB\x06\n" +
	"\x04body\"M\n" +
	"\x06Resume\x12\x1b\n" +
	"\ttrack_uid\x18\x01 \x01(\tR\btrackUid\x12&\n" +
	"\x0flast_client_seq\x18\x02 \x01(\x04R\rlastClientSeq\"\x84\x01\n" +
	"\n" +
	"TrackStart\x12/\n" +
	"\blocation\x18\x01 \x01(\v2\x13.tracking.v2.LatLngR\blocation\x12)\n" +
	"\x05route\x18\x02 \x03(\v2\x13.tracking.v2.LatLngR\x05route\x12\x1a\n" +
	"\bmetadata\x18\x03 \x01(\fR\bmetadata\"(\n" +
	"\tTrackStop\x12\x1b\n" +
	"\ttrack_uid\x18\x01 \x01(\tR\btrackUid\"t\n" +
	"\vLocationAdd\x12\x1b\n" +
	"\ttrack_uid\x18\x01 \x01(\tR\btrackUid\x12\x1d\n" +
	"\n" +
	"client_seq\x18\x02 \x01(\x04R\tclientSeq\x12)\n" +
	"\x05point\x18\x03 \x01(\v2\x13.tracking.v2.LatLngR\x05point\"x\n" +
	"\rLocationBatch\x12\x1b\n" +
	"\ttrack_uid\x18\x01 \x01(\tR\btrackUid\x12\x1d\n" +
	"\n" +
	"client_seq\x18\x02 \x01(\x04R\tclientSeq\x12+\n" +
	"\x06points\x18\x03 \x03(\v2\x13.tracking.v2.LatLngR\x06points\"\xa2\x01\n" +
	"\tSubscribe\x12\x1d\n" +
	"\n" +
	"device_uid\x18\x01 \x01(\tR\tdeviceUid\x12*\n" +
	"\x0einclude_events\x18\x02 \x01(\bH\x00R\rincludeEvents\x88\x01\x01\x127\n" +
	"\x18min_location_interval_ms\x18\x03 \x01(\rR\x15minLocationIntervalMsB\x11\n" +
	"\x0f_include_events\",\n" +
	"\vUnsubscribe\x12\x1d\n" +
	"\n" +
	"device_uid\x18\x01 \x01(\tR\tdeviceUid\"\x06\n" +
	"\x04Ping\"w\n" +
	"\x05Event\x12\x1b\n" +
	"\ttrack_uid\x18\x01 \x01(\tR\btrackUid\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12&\n" +
	"\ftimestamp_ms\x18\x03 \x01(\x03H\x00R\vtimestampMs\x88\x01\x01B\x0f\n" +
	"\r_timestamp_ms\"\x8d\x01\n" +
	"\n" +
	"CommandAck\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x125\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1d.tracking.v2.CommandAckStatusR\x06status\x12\x1d\n" +
	"\amessage\x18\x03 \x01(\tH\x00R\amessage\x88\x01\x01B\n" +
	"\n" +
	"\b_message\"\x8d\x06\n" +
	"\tServerMsg\x12*\n" +
	"\x05hello\x18\x01 \x01(\v2\x12.tracking.v2.HelloH\x00R\x05hello\x123\n" +
	"\brelocate\x18\x02 \x01(\v2\x15.tracking.v2.RelocateH\x00R\brelocate\x124\n" +
	"\tresume_ok\x18\x03 \x01(\v2\x15.tracking.v2.ResumeOkH\x00R\bresumeOk\x12@\n" +
	"\rtrack_started\x18\x04 \x01(\v2\x19.tracking.v2.TrackStartedH\x00R\ftrackStarted\x12@\n" +
	"\rtrack_stopped\x18\x05 \x01(\v2\x19.tracking.v2.TrackStoppedH\x00R\ftrackStopped\x12C\n" +
	"\x0elocation_added\x18\x06 \x01(\v2\x1a.tracking.v2.LocationAddedH\x00R\rlocationAdded\x129\n" +
	"\n" +
	"subscribed\x18\a \x01(\v2\x17.tracking.v2.SubscribedH\x00R\n" +
	"subscribed\x12R\n" +
	"\x13listener_subscribed\x18\b \x01(\v2\x1f.tracking.v2.ListenerSubscribedH\x00R\x12listenerSubscribed\x12*\n" +
	"\x05error\x18\t \x01(\v2\x12.tracking.v2.ErrorH\x00R\x05error\x12'\n" +
	"\x04pong\x18\n" +
	" \x01(\v2\x11.tracking.v2.PongH\x00R\x04pong\x12:\n" +
	"\vevent_added\x18\v \x01(\v2\x17.tracking.v2.EventAddedH\x00R\n" +
	"eventAdded\x120\n" +
	"\acommand\x18\f \x01(\v2\x14.tracking.v2.CommandH\x00R\acommand\x12F\n" +
	"\x0fdevice_presence\x18\r \x01(\v2\x1b.tracking.v2.DevicePresenceH\x00R\x0edevicePresenceB\x06\n" +
	"\x04body\"6\n" +
	"\x05Hello\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x14\n" +
	"\x05shard\x18\x02 \x01(\rR\x05shard\"L\n" +
	"\bRelocate\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12$\n" +
	"\x0eretry_after_ms\x18\x02 \x01(\rR\fretryAfterMs\"M\n" +
	"\bResumeOk\x12\x1b\n" +
	"\ttrack_uid\x18\x01 \x01(\tR\btrackUid\x12$\n" +
	"\x0elast_acked_seq\x18\x02 \x01(\x04R\flastAckedSeq\"G\n" +
	"\fTrackStarted\x12\x1b\n" +
	"\ttrack_uid\x18\x01 \x01(\tR\btrackUid\x12\x1a\n" +
	"\bmetadata\x18\x02 \x01(\fR\bmetadata\"+\n" +
	"\fTrackStopped\x12\x1b\n" +
	"\ttrack_uid\x18\x01 \x01(\tR\btrackUid\"\x95\x01\n" +
	"\rLocationAdded\x12\x1d\n" +
	"\n" +
	"device_uid\x18\x01 \x01(\tR\tdeviceUid\x12\x1b\n" +
	"\ttrack_uid\x18\x02 \x01(\tR\btrackUid\x12)\n" +
	"\x05point\x18\x03 \x01(\v2\x13.tracking.v2.LatLngR\x05point\x12\x1d\n" +
	"\n" +
	"client_seq\x18\x04 \x01(\x04R\tclientSeq\"\x86\x04\n" +
	"\n" +
	"Subscribed\x12\x1d\n" +
	"\n" +
	"device_uid\x18\x01 \x01(\tR\tdeviceUid\x12\x1b\n" +
	"\ttrack_uid\x18\x02 \x01(\tR\btrackUid\x128\n" +
	"\rlast_location\x18\x03 \x01(\v2\x13.tracking.v2.LatLngR\flastLocation\x12)\n" +
	"\x05route\x18\x04 \x03(\v2\x13.tracking.v2.LatLngR\x05route\x121\n" +
	"\tlocations\x18\x05 \x03(\v2\x13.tracking.v2.LatLngR\tlocations\x12-\n" +
	"\x12estimated_distance\x18\x06 \x01(\x01R\x11estimatedDistance\x12-\n" +
	"\x12estimated_duration\x18\a \x01(\x01R\x11estimatedDuration\x12.\n" +
	"\x13start_location_name\x18\b \x01(\tR\x11startLocationName\x12*\n" +
	"\x11end_location_name\x18\t \x01(\tR\x0fendLocationName\x12\x1a\n" +
	"\bmetadata\x18\n" +
	" \x01(\fR\bmetadata\x12\x16\n" +
	"\x06online\x18\v \x01(\bR\x06online\x12%\n" +
	"\flast_seen_ms\x18\f \x01(\x03H\x00R\n" +
	"lastSeenMs\x88\x01\x01B\x0f\n" +
	"\r_last_seen_ms\"\x14\n" +
	"\x12ListenerSubscribed\"\xbb\x01\n" +
	"\x05Error\x12*\n" +
	"\x04code\x18\x01 \x01(\x0e2\x16.tracking.v2.ErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12 \n" +
	"\ttrack_uid\x18\x03 \x01(\tH\x00R\btrackUid\x88\x01\x01\x12)\n" +
	"\x0eretry_after_ms\x18\x04 \x01(\rH\x01R\fretryAfterMs\x88\x01\x01B\f\n" +
	"\n" +
	"_track_uidB\x11\n" +
	"\x0f_retry_after_ms\"\x06\n" +
	"\x04Pong\"\x9b\x01\n" +
	"\n" +
	"EventAdded\x12\x1d\n" +
	"\n" +
	"device_uid\x18\x01 \x01(\tR\tdeviceUid\x12\x1b\n" +
	"\ttrack_uid\x18\x02 \x01(\tR\btrackUid\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12&\n" +
	"\ftimestamp_ms\x18\x04 \x01(\x03H\x00R\vtimestampMs\x88\x01\x01B\x0f\n" +
	"\r_timestamp_ms\"{\n" +
	"\aCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12&\n" +
	"\ftimestamp_ms\x18\x03 \x01(\x03H\x00R\vtimestampMs\x88\x01\x01B\x0f\n" +
	"\r_timestamp_ms\"\x7f\n" +
	"\x0eDevicePresence\x12\x1d\n" +
	"\n" +
	"device_uid\x18\x01 \x01(\tR\tdeviceUid\x12\x16\n" +
	"\x06online\x18\x02 \x01(\bR\x06online\x12%\n" +
	"\flast_seen_ms\x18\x03 \x01(\x03H\x00R\n" +
	"lastSeenMs\x88\x01\x01B\x0f\n" +
	"\r_last_seen_ms*\x91\x01\n" +
	"\x10CommandAckStatus\x12\"\n" +
	"\x1eCOMMAND_ACK_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15COMMAND_ACK_STATUS_OK\x10\x01\x12\x1f\n" +
	"\x1bCOMMAND_ACK_STATUS_REJECTED\x10\x02\x12\x1d\n" +
	"\x19COMMAND_ACK_STATUS_FAILED\x10\x03*\xc2\x01\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fERROR_CODE_AUTH\x10\x01\x12\x1e\n" +
	"\x1aERROR_CODE_TRACK_NOT_FOUND\x10\x02\x12\x15\n" +
	"\x11ERROR_CODE_FENCED\x10\x03\x12\x18\n" +
	"\x14ERROR_CODE_TRY_AGAIN\x10\x04\x12\x16\n" +
	"\x12ERROR_CODE_INVALID\x10\x05\x12\x1b\n" +
	"\x17ERROR_CODE_UNAUTHORIZED\x10\x06B2Z0github.com/pickpoint/go-sdk/tracking/v2;trackingb\x06proto3"

var (
	file_tracking_v2_messages_proto_rawDescOnce sync.Once
	file_tracking_v2_messages_proto_rawDescData []byte
)

func file_tracking_v2_messages_proto_rawDescGZIP() []byte {
	file_tracking_v2_messages_proto_rawDescOnce.Do(func() {
		file_tracking_v2_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tracking_v2_messages_proto_rawDesc), len(file_tracking_v2_messages_proto_rawDesc)))
	})
	return file_tracking_v2_messages_proto_rawDescData
}

var file_tracking_v2_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_tracking_v2_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_tracking_v2_messages_proto_goTypes = []any{
	(CommandAckStatus)(0),      // 0: tracking.v2.CommandAckStatus
	(ErrorCode)(0),             // 1: tracking.v2.ErrorCode
	(*LatLng)(nil),             // 2: tracking.v2.LatLng
	(*ClientMsg)(nil),          // 3: tracking.v2.ClientMsg
	(*Resume)(nil),             // 4: tracking.v2.Resume
	(*TrackStart)(nil),         // 5: tracking.v2.TrackStart
	(*TrackStop)(nil),          // 6: tracking.v2.TrackStop
	(*LocationAdd)(nil),        // 7: tracking.v2.LocationAdd
	(*LocationBatch)(nil),      // 8: tracking.v2.LocationBatch
	(*Subscribe)(nil),          // 9: tracking.v2.Subscribe
	(*Unsubscribe)(nil),        // 10: tracking.v2.Unsubscribe
	(*Ping)(nil),               // 11: tracking.v2.Ping
	(*Event)(nil),              // 12: tracking.v2.Event
	(*CommandAck)(nil),         // 13: tracking.v2.CommandAck
	(*ServerMsg)(nil),          // 14: tracking.v2.ServerMsg
	(*Hello)(nil),              // 15: tracking.v2.Hello
	(*Relocate)(nil),           // 16: tracking.v2.Relocate
	(*ResumeOk)(nil),           // 17: tracking.v2.ResumeOk
	(*TrackStarted)(nil),       // 18: tracking.v2.TrackStarted
	(*TrackStopped)(nil),       // 19: tracking.v2.TrackStopped
	(*LocationAdded)(nil),      // 20: tracking.v2.LocationAdded
	(*Subscribed)(nil),         // 21: tracking.v2.Subscribed
	(*ListenerSubscribed)(nil), // 22: tracking.v2.ListenerSubscribed
	(*Error)(nil),              // 23: tracking.v2.Error
	(*Pong)(nil),               // 24: tracking.v2.Pong
	(*EventAdded)(nil),         // 25: tracking.v2.EventAdded
	(*Command)(nil),            // 26: tracking.v2.Command
	(*DevicePresence)(nil),     // 27: tracking.v2.DevicePresence
}
var file_tracking_v2_messages_proto_depIdxs = []int32{
	4,  // 0: tracking.v2.ClientMsg.resume:type_name -> tracking.v2.Resume
	5,  // 1: tracking.v2.ClientMsg.track_start:type_name -> tracking.v2.TrackStart
	6,  // 2: tracking.v2.ClientMsg.track_stop:type_name -> tracking.v2.TrackStop
	7,  // 3: tracking.v2.ClientMsg.location_add:type_name -> tracking.v2.LocationAdd
	8,  // 4: tracking.v2.ClientMsg.location_batch:type_name -> tracking.v2.LocationBatch
	9,  // 5: tracking.v2.ClientMsg.subscribe:type_name -> tracking.v2.Subscribe
	10, // 6: tracking.v2.ClientMsg.unsubscribe:type_name -> tracking.v2.Unsubscribe
	11, // 7: tracking.v2.ClientMsg.ping:type_name -> tracking.v2.Ping
	12, // 8: tracking.v2.ClientMsg.event:type_name -> tracking.v2.Event
	13, // 9: tracking.v2.ClientMsg.command_ack:type_name -> tracking.v2.CommandAck
	2,  // 10: tracking.v2.TrackStart.location:type_name -> tracking.v2.LatLng
	2,  // 11: tracking.v2.TrackStart.route:type_name -> tracking.v2.LatLng
	2,  // 12: tracking.v2.LocationAdd.point:type_name -> tracking.v2.LatLng
	2,  // 13: tracking.v2.LocationBatch.points:type_name -> tracking.v2.LatLng
	0,  // 14: tracking.v2.CommandAck.status:type_name -> tracking.v2.CommandAckStatus
	15, // 15: tracking.v2.ServerMsg.hello:type_name -> tracking.v2.Hello
	16, // 16: tracking.v2.ServerMsg.relocate:type_name -> tracking.v2.Relocate
	17, // 17: tracking.v2.ServerMsg.resume_ok:type_name -> tracking.v2.ResumeOk
	18, // 18: tracking.v2.ServerMsg.track_started:type_name -> tracking.v2.TrackStarted
	19, // 19: tracking.v2.ServerMsg.track_stopped:type_name -> tracking.v2.TrackStopped
	20, // 20: tracking.v2.ServerMsg.location_added:type_name -> tracking.v2.LocationAdded
	21, // 21: tracking.v2.ServerMsg.subscribed:type_name -> tracking.v2.Subscribed
	22, // 22: tracking.v2.ServerMsg.listener_subscribed:type_name -> tracking.v2.ListenerSubscribed
	23, // 23: tracking.v2.ServerMsg.error:type_name -> tracking.v2.Error
	24, // 24: tracking.v2.ServerMsg.pong:type_name -> tracking.v2.Pong
	25, // 25: tracking.v2.ServerMsg.event_added:type_name -> tracking.v2.EventAdded
	26, // 26: tracking.v2.ServerMsg.command:type_name -> tracking.v2.Command
	27, // 27: tracking.v2.ServerMsg.device_presence:type_name -> tracking.v2.DevicePresence
	2,  // 28: tracking.v2.LocationAdded.point:type_name -> tracking.v2.LatLng
	2,  // 29: tracking.v2.Subscribed.last_location:type_name -> tracking.v2.LatLng
	2,  // 30: tracking.v2.Subscribed.route:type_name -> tracking.v2.LatLng
	2,  // 31: tracking.v2.Subscribed.locations:type_name -> tracking.v2.LatLng
	1,  // 32: tracking.v2.Error.code:type_name -> tracking.v2.ErrorCode
	33, // [33:33] is the sub-list for method output_type
	33, // [33:33] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_tracking_v2_messages_proto_init() }
func file_tracking_v2_messages_proto_init() {
	if File_tracking_v2_messages_proto != nil {
		return
	}
	file_tracking_v2_messages_proto_msgTypes[0].OneofWrappers = []any{}
	file_tracking_v2_messages_proto_msgTypes[1].OneofWrappers = []any{
		(*ClientMsg_Resume)(nil),
		(*ClientMsg_TrackStart)(nil),
		(*ClientMsg_TrackStop)(nil),
		(*ClientMsg_LocationAdd)(nil),
		(*ClientMsg_LocationBatch)(nil),
		(*ClientMsg_Subscribe)(nil),
		(*ClientMsg_Unsubscribe)(nil),
		(*ClientMsg_Ping)(nil),
		(*ClientMsg_Event)(nil),
		(*ClientMsg_CommandAck)(nil),
	}
	file_tracking_v2_messages_proto_msgTypes[7].OneofWrappers = []any{}
	file_tracking_v2_messages_proto_msgTypes[10].OneofWrappers = []any{}
	file_tracking_v2_messages_proto_msgTypes[11].OneofWrappers = []any{}
	file_tracking_v2_messages_proto_msgTypes[12].OneofWrappers = []any{
		(*ServerMsg_Hello)(nil),
		(*ServerMsg_Relocate)(nil),
		(*ServerMsg_ResumeOk)(nil),
		(*ServerMsg_TrackStarted)(nil),
		(*ServerMsg_TrackStopped)(nil),
		(*ServerMsg_LocationAdded)(nil),
		(*ServerMsg_Subscribed)(nil),
		(*ServerMsg_ListenerSubscribed)(nil),
		(*ServerMsg_Error)(nil),
		(*ServerMsg_Pong)(nil),
		(*ServerMsg_EventAdded)(nil),
		(*ServerMsg_Command)(nil),
		(*ServerMsg_DevicePresence)(nil),
	}
	file_tracking_v2_messages_proto_msgTypes[19].OneofWrappers = []any{}
	file_tracking_v2_messages_proto_msgTypes[21].OneofWrappers = []any{}
	file_tracking_v2_messages_proto_msgTypes[23].OneofWrappers = []any{}
	file_tracking_v2_messages_proto_msgTypes[24].OneofWrappers = []any{}
	file_tracking_v2_messages_proto_msgTypes[25].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tracking_v2_messages_proto_rawDesc), len(file_tracking_v2_messages_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tracking_v2_messages_proto_goTypes,
		DependencyIndexes: file_tracking_v2_messages_proto_depIdxs,
		EnumInfos:         file_tracking_v2_messages_proto_enumTypes,
		MessageInfos:      file_tracking_v2_messages_proto_msgTypes,
	}.Build()
	File_tracking_v2_messages_proto = out.File
	file_tracking_v2_messages_proto_goTypes = nil
	file_tracking_v2_messages_proto_depIdxs = nil
}
