// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: tracking/v2/service.proto

package tracking

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Tracking_Session_FullMethodName = "/tracking.v2.Tracking/Session"
)

// TrackingClient is the client API for Tracking service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Public bidi session (mounted under /v2/tracking/grpc).
// Named Session (not Connect) to avoid clashing with tonic client's connect().
type TrackingClient interface {
	Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMsg, ServerMsg], error)
}

type trackingClient struct {
	cc grpc.ClientConnInterface
}

func NewTrackingClient(cc grpc.ClientConnInterface) TrackingClient {
	return &trackingClient{cc}
}

func (c *trackingClient) Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMsg, ServerMsg], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Tracking_ServiceDesc.Streams[0], Tracking_Session_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientMsg, ServerMsg]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Tracking_SessionClient = grpc.BidiStreamingClient[ClientMsg, ServerMsg]

// TrackingServer is the server API for Tracking service.
// All implementations must embed UnimplementedTrackingServer
// for forward compatibility.
//
// Public bidi session (mounted under /v2/tracking/grpc).
// Named Session (not Connect) to avoid clashing with tonic client's connect().
type TrackingServer interface {
	Session(grpc.BidiStreamingServer[ClientMsg, ServerMsg]) error
	mustEmbedUnimplementedTrackingServer()
}

// UnimplementedTrackingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTrackingServer struct{}

func (UnimplementedTrackingServer) Session(grpc.BidiStreamingServer[ClientMsg, ServerMsg]) error {
	return status.Error(codes.Unimplemented, "method Session not implemented")
}
func (UnimplementedTrackingServer) mustEmbedUnimplementedTrackingServer() {}
func (UnimplementedTrackingServer) testEmbeddedByValue()                  {}

// UnsafeTrackingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrackingServer will
// result in compilation errors.
type UnsafeTrackingServer interface {
	mustEmbedUnimplementedTrackingServer()
}

func RegisterTrackingServer(s grpc.ServiceRegistrar, srv TrackingServer) {
	// If the following call panics, it indicates UnimplementedTrackingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Tracking_ServiceDesc, srv)
}

func _Tracking_Session_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TrackingServer).Session(&grpc.GenericServerStream[ClientMsg, ServerMsg]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Tracking_SessionServer = grpc.BidiStreamingServer[ClientMsg, ServerMsg]

// Tracking_ServiceDesc is the grpc.ServiceDesc for Tracking service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Tracking_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tracking.v2.Tracking",
	HandlerType: (*TrackingServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Session",
			Handler:       _Tracking_Session_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "tracking/v2/service.proto",
}

const (
	Mesh_Forward_FullMethodName = "/tracking.v2.Mesh/Forward"
	Mesh_HandOff_FullMethodName = "/tracking.v2.Mesh/HandOff"
)

// MeshClient is the client API for Mesh service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Inter-node mesh (MESH_ADDR only, not on public Ingress).
type MeshClient interface {
	Forward(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[MeshEnvelope, MeshAck], error)
	HandOff(ctx context.Context, in *HandOffRequest, opts ...grpc.CallOption) (*HandOffResponse, error)
}

type meshClient struct {
	cc grpc.ClientConnInterface
}

func NewMeshClient(cc grpc.ClientConnInterface) MeshClient {
	return &meshClient{cc}
}

func (c *meshClient) Forward(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[MeshEnvelope, MeshAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Mesh_ServiceDesc.Streams[0], Mesh_Forward_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MeshEnvelope, MeshAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Mesh_ForwardClient = grpc.BidiStreamingClient[MeshEnvelope, MeshAck]

func (c *meshClient) HandOff(ctx context.Context, in *HandOffRequest, opts ...grpc.CallOption) (*HandOffResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandOffResponse)
	err := c.cc.Invoke(ctx, Mesh_HandOff_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MeshServer is the server API for Mesh service.
// All implementations must embed UnimplementedMeshServer
// for forward compatibility.
//
// Inter-node mesh (MESH_ADDR only, not on public Ingress).
type MeshServer interface {
	Forward(grpc.BidiStreamingServer[MeshEnvelope, MeshAck]) error
	HandOff(context.Context, *HandOffRequest) (*HandOffResponse, error)
	mustEmbedUnimplementedMeshServer()
}

// UnimplementedMeshServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMeshServer struct{}

func (UnimplementedMeshServer) Forward(grpc.BidiStreamingServer[MeshEnvelope, MeshAck]) error {
	return status.Error(codes.Unimplemented, "method Forward not implemented")
}
func (UnimplementedMeshServer) HandOff(context.Context, *HandOffRequest) (*HandOffResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandOff not implemented")
}
func (UnimplementedMeshServer) mustEmbedUnimplementedMeshServer() {}
func (UnimplementedMeshServer) testEmbeddedByValue()              {}

// UnsafeMeshServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MeshServer will
// result in compilation errors.
type UnsafeMeshServer interface {
	mustEmbedUnimplementedMeshServer()
}

func RegisterMeshServer(s grpc.ServiceRegistrar, srv MeshServer) {
	// If the following call panics, it indicates UnimplementedMeshServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Mesh_ServiceDesc, srv)
}

func _Mesh_Forward_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MeshServer).Forward(&grpc.GenericServerStream[MeshEnvelope, MeshAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Mesh_ForwardServer = grpc.BidiStreamingServer[MeshEnvelope, MeshAck]

func _Mesh_HandOff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandOffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshServer).HandOff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mesh_HandOff_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshServer).HandOff(ctx, req.(*HandOffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Mesh_ServiceDesc is the grpc.ServiceDesc for Mesh service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Mesh_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tracking.v2.Mesh",
	HandlerType: (*MeshServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HandOff",
			Handler:    _Mesh_HandOff_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Forward",
			Handler:       _Mesh_Forward_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "tracking/v2/service.proto",
}
