// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: tracking/v2/service.proto

package tracking

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MeshEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceUid     string                 `protobuf:"bytes,1,opt,name=device_uid,json=deviceUid,proto3" json:"device_uid,omitempty"`
	Event         *ServerMsg             `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeshEnvelope) Reset() {
	*x = MeshEnvelope{}
	mi := &file_tracking_v2_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshEnvelope) ProtoMessage() {}

func (x *MeshEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_tracking_v2_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshEnvelope.ProtoReflect.Descriptor instead.
func (*MeshEnvelope) Descriptor() ([]byte, []int) {
	return file_tracking_v2_service_proto_rawDescGZIP(), []int{0}
}

func (x *MeshEnvelope) GetDeviceUid() string {
	if x != nil {
		return x.DeviceUid
	}
	return ""
}

func (x *MeshEnvelope) GetEvent() *ServerMsg {
	if x != nil {
		return x.Event
	}
	return nil
}

type MeshAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeshAck) Reset() {
	*x = MeshAck{}
	mi := &file_tracking_v2_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshAck) ProtoMessage() {}

func (x *MeshAck) ProtoReflect() protoreflect.Message {
	mi := &file_tracking_v2_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshAck.ProtoReflect.Descriptor instead.
func (*MeshAck) Descriptor() ([]byte, []int) {
	return file_tracking_v2_service_proto_rawDescGZIP(), []int{1}
}

func (x *MeshAck) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type HandOffRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shard         uint32                 `protobuf:"varint,1,opt,name=shard,proto3" json:"shard,omitempty"`
	Epoch         uint64                 `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	FromNode      string                 `protobuf:"bytes,3,opt,name=from_node,json=fromNode,proto3" json:"from_node,omitempty"`
	ToNode        string                 `protobuf:"bytes,4,opt,name=to_node,json=toNode,proto3" json:"to_node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandOffRequest) Reset() {
	*x = HandOffRequest{}
	mi := &file_tracking_v2_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandOffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandOffRequest) ProtoMessage() {}

func (x *HandOffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tracking_v2_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandOffRequest.ProtoReflect.Descriptor instead.
func (*HandOffRequest) Descriptor() ([]byte, []int) {
	return file_tracking_v2_service_proto_rawDescGZIP(), []int{2}
}

func (x *HandOffRequest) GetShard() uint32 {
	if x != nil {
		return x.Shard
	}
	return 0
}

func (x *HandOffRequest) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *HandOffRequest) GetFromNode() string {
	if x != nil {
		return x.FromNode
	}
	return ""
}

func (x *HandOffRequest) GetToNode() string {
	if x != nil {
		return x.ToNode
	}
	return ""
}

type HandOffResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandOffResponse) Reset() {
	*x = HandOffResponse{}
	mi := &file_tracking_v2_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandOffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandOffResponse) ProtoMessage() {}

func (x *HandOffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tracking_v2_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandOffResponse.ProtoReflect.Descriptor instead.
func (*HandOffResponse) Descriptor() ([]byte, []int) {
	return file_tracking_v2_service_proto_rawDescGZIP(), []int{3}
}

func (x *HandOffResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HandOffResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_tracking_v2_service_proto protoreflect.FileDescriptor

const file_tracking_v2_service_proto_rawDesc = "" +
	"\n" +
	"\x19tracking/v2/service.proto\x12\vtracking.v2\x1a\x1atracking/v2/messages.proto\"[\n" +
	"\fMeshEnvelope\x12\x1d\n" +
	"\n" +
	"device_uid\x18\x01 \x01(\tR\tdeviceUid\x12,\n" +
	"\x05event\x18\x02 \x01(\v2\x16.tracking.v2.ServerMsgR\x05event\"\x19\n" +
	"\aMeshAck\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"r\n" +
	"\x0eHandOffRequest\x12\x14\n" +
	"\x05shard\x18\x01 \x01(\rR\x05shard\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x04R\x05epoch\x12\x1b\n" +
	"\tfrom_node\x18\x03 \x01(\tR\bfromNode\x12\x17\n" +
	"\ato_node\x18\x04 \x01(\tR\x06toNode\";\n" +
	"\x0fHandOffResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2I\n" +
	"\bTracking\x12=\n" +
	"\aSession\x12\x16.tracking.v2.ClientMsg\x1a\x16.tracking.v2.ServerMsg(\x010\x012\x8c\x01\n" +
	"\x04Mesh\x12>\n" +
	"\aForward\x12\x19.tracking.v2.MeshEnvelope\x1a\x14.tracking.v2.MeshAck(\x010\x01\x12D\n" +
	"\aHandOff\x12\x1b.tracking.v2.HandOffRequest\x1a\x1c.tracking.v2.HandOffResponseB2Z0github.com/pickpoint/go-sdk/tracking/v2;trackingb\x06proto3"

var (
	file_tracking_v2_service_proto_rawDescOnce sync.Once
	file_tracking_v2_service_proto_rawDescData []byte
)

func file_tracking_v2_service_proto_rawDescGZIP() []byte {
	file_tracking_v2_service_proto_rawDescOnce.Do(func() {
		file_tracking_v2_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tracking_v2_service_proto_rawDesc), len(file_tracking_v2_service_proto_rawDesc)))
	})
	return file_tracking_v2_service_proto_rawDescData
}

var file_tracking_v2_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_tracking_v2_service_proto_goTypes = []any{
	(*MeshEnvelope)(nil),    // 0: tracking.v2.MeshEnvelope
	(*MeshAck)(nil),         // 1: tracking.v2.MeshAck
	(*HandOffRequest)(nil),  // 2: tracking.v2.HandOffRequest
	(*HandOffResponse)(nil), // 3: tracking.v2.HandOffResponse
	(*ServerMsg)(nil),       // 4: tracking.v2.ServerMsg
	(*ClientMsg)(nil),       // 5: tracking.v2.ClientMsg
}
var file_tracking_v2_service_proto_depIdxs = []int32{
	4, // 0: tracking.v2.MeshEnvelope.event:type_name -> tracking.v2.ServerMsg
	5, // 1: tracking.v2.Tracking.Session:input_type -> tracking.v2.ClientMsg
	0, // 2: tracking.v2.Mesh.Forward:input_type -> tracking.v2.MeshEnvelope
	2, // 3: tracking.v2.Mesh.HandOff:input_type -> tracking.v2.HandOffRequest
	4, // 4: tracking.v2.Tracking.Session:output_type -> tracking.v2.ServerMsg
	1, // 5: tracking.v2.Mesh.Forward:output_type -> tracking.v2.MeshAck
	3, // 6: tracking.v2.Mesh.HandOff:output_type -> tracking.v2.HandOffResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_tracking_v2_service_proto_init() }
func file_tracking_v2_service_proto_init() {
	if File_tracking_v2_service_proto != nil {
		return
	}
	file_tracking_v2_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tracking_v2_service_proto_rawDesc), len(file_tracking_v2_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_tracking_v2_service_proto_goTypes,
		DependencyIndexes: file_tracking_v2_service_proto_depIdxs,
		MessageInfos:      file_tracking_v2_service_proto_msgTypes,
	}.Build()
	File_tracking_v2_service_proto = out.File
	file_tracking_v2_service_proto_goTypes = nil
	file_tracking_v2_service_proto_depIdxs = nil
}
